#include "orbitlab/physics.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>

using namespace orbitlab;

namespace {

struct MissionObject {
  Vehicle vehicle;
  std::string color;
  std::vector<Sample> samples;
};

std::string js_string(const std::string& value) {
  std::ostringstream out;
  out << '"';
  for (char c : value) {
    if (c == '"' || c == '\\') out << '\\';
    out << c;
  }
  out << '"';
  return out.str();
}

void write_vec(std::ostream& out, const Vec3& v) {
  out << '[' << v.x << ',' << v.y << ',' << v.z << ']';
}

Vehicle vehicle(std::string id, std::string name, std::string kind,
                std::string, double altitude_km, double eccentricity,
                double inclination_deg, double raan_deg, double argp_deg,
                double anomaly_deg, double mass_kg, double area_m2,
                double cd, double cr) {
  const Elements elements{radius_earth + altitude_km, eccentricity, rad(inclination_deg),
                          rad(raan_deg), rad(argp_deg), rad(anomaly_deg)};
  return {std::move(id),std::move(name),std::move(kind),mass_kg,area_m2,cd,cr,from_elements(elements)};
}

void write_dataset(const std::filesystem::path& path, std::vector<MissionObject>& objects,
                   double duration_s, double output_step_s, double integration_step_s) {
  std::ofstream out(path);
  if (!out) throw std::runtime_error("cannot open output file: " + path.string());
  out << std::setprecision(10);

  // Find the closest fleet/debris encounter across the propagated grid.
  double min_distance=std::numeric_limits<double>::infinity();
  std::size_t min_i=0, min_a=0, min_b=1;
  for (std::size_t a=0;a<objects.size();++a) for (std::size_t b=a+1;b<objects.size();++b) {
    const std::size_t n=std::min(objects[a].samples.size(),objects[b].samples.size());
    for (std::size_t i=0;i<n;++i) {
      const double d=norm(objects[a].samples[i].state.r-objects[b].samples[i].state.r);
      if (d<min_distance) { min_distance=d; min_i=i; min_a=a; min_b=b; }
    }
  }

  const auto& ca=objects[min_a].samples[min_i];
  const auto& cb=objects[min_b].samples[min_i];
  const double rel_speed=norm(ca.state.v-cb.state.v);

  out << "// Generated by the OrbitLab C++20 high-fidelity propagator.\n";
  out << "window.ORBITLAB_DATA={\n";
  out << "meta:{epoch:\"2026-09-12T00:00:00.000Z\",frame:\"GCRF / ECI (J2000)\","
         "gravity:\"EGM-96 point mass + J2\",integrator:\"RK4 fixed-step\","
      << "duration_s:" << duration_s << ",output_step_s:" << output_step_s
      << ",integration_step_s:" << integration_step_s
      << ",mu:" << mu_earth << ",radius:" << radius_earth << ",j2:" << j2_earth << "},\n";
  out << "forces:["
      << "{id:\"2body\",label:\"Central gravity\",status:\"ACTIVE\",order:0},"
      << "{id:\"j2\",label:\"J₂ oblateness\",status:\"ACTIVE\",order:2},"
      << "{id:\"drag\",label:\"Co-rotating drag\",status:\"ACTIVE\",order:1},"
      << "{id:\"srp\",label:\"Solar radiation pressure\",status:\"ACTIVE / ECLIPSE\",order:1}],\n";
  out << "conjunction:{a:" << js_string(objects[min_a].vehicle.id)
      << ",b:" << js_string(objects[min_b].vehicle.id)
      << ",sample:" << min_i << ",t_s:" << ca.t_s
      << ",miss_km:" << min_distance << ",relative_speed_km_s:" << rel_speed
      << ",classification:" << js_string(min_distance<5.0?"SCREEN":"NOMINAL") << "},\n";
  out << "objects:[\n";
  for (std::size_t oi=0;oi<objects.size();++oi) {
    const auto& object=objects[oi];
    const double baseline=object.samples.front().energy;
    out << "{id:" << js_string(object.vehicle.id) << ",name:" << js_string(object.vehicle.name)
        << ",kind:" << js_string(object.vehicle.kind) << ",color:" << js_string(object.color)
        << ",mass_kg:" << object.vehicle.mass_kg << ",area_m2:" << object.vehicle.area_m2
        << ",cd:" << object.vehicle.cd << ",cr:" << object.vehicle.cr
        << ",period_s:" << period_s(object.vehicle.initial) << ",samples:[\n";
    for (std::size_t i=0;i<object.samples.size();++i) {
      const auto& s=object.samples[i];
      out << '[' << s.t_s << ','; write_vec(out,s.state.r); out << ','; write_vec(out,s.state.v);
      out << "," << s.elements.a_km << ',' << s.elements.e << ',' << deg(s.elements.i_rad)
          << ',' << deg(s.elements.raan_rad) << ',' << deg(s.elements.argp_rad)
          << ',' << deg(s.elements.nu_rad) << ',' << (s.energy-baseline) << ',' << s.density << ']';
      if (i+1<object.samples.size()) out << ',';
      out << '\n';
    }
    out << "]}" << (oi+1<objects.size()?",":"") << '\n';
  }
  out << "]};\n";
}

} // namespace

int main(int argc, char** argv) {
  try {
    const std::filesystem::path output=argc>1 ? argv[1] : "telemetry.js";
    constexpr double duration_s=6.0*3600.0;
    constexpr double integration_step_s=10.0;
    constexpr double output_step_s=60.0;
    const ForceModel model{true,true,true};

    std::vector<MissionObject> objects{
      {vehicle("AUR-01","AURORA-1","EARTH OBSERVATION","#63e6d1",700.0,0.0012,98.20,22.0,0.0,0.0,620.0,9.8,2.18,1.32),"#63e6d1",{}},
      {vehicle("KST-14","KESTREL-14","RESEARCH CUBESAT","#e8be5a",512.0,0.0038,51.64,116.0,248.0,132.0,18.0,0.14,2.30,1.25),"#e8be5a",{}},
      // A deliberately constructed ascending-node crossing: useful for validating
      // high-relative-velocity screening without claiming a real-world event.
      {vehicle("RB-2481","SL-8 R/B 1979-018C","DEBRIS / ROCKET BODY","#ef6a54",702.0,0.0012,51.60,22.0,0.0,0.0,1450.0,12.6,2.35,1.18),"#ef6a54",{}},
      {vehicle("LYR-03","LYRA RELAY-3","COMMUNICATIONS","#879df1",20200.0,0.012,55.0,302.0,12.0,218.0,1900.0,18.0,2.2,1.4),"#879df1",{}}
    };
    for (auto& object:objects)
      object.samples=propagate(object.vehicle,model,duration_s,integration_step_s,output_step_s);
    std::filesystem::create_directories(output.parent_path().empty()?".":output.parent_path());
    write_dataset(output,objects,duration_s,output_step_s,integration_step_s);
    std::cout << "OrbitLab propagated " << objects.size() << " objects across " << duration_s/3600.0
              << " h; wrote " << output << '\n';
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "orbitlab: " << error.what() << '\n';
    return 1;
  }
}
